/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CartStatus.
* @enum {}
* @readonly
*/
export default class CartStatus {
        /**
         * value: "pending"
         * @const
         */
        pending = "pending";

        /**
         * value: "canceled"
         * @const
         */
        canceled = "canceled";

        /**
         * value: "authorized"
         * @const
         */
        authorized = "authorized";

        /**
         * value: "closed"
         * @const
         */
        closed = "closed";


    /**
    * Returns a <code>CartStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CartStatus} The enum <code>CartStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
