/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ItemProperty from './ItemProperty';

/**
* The CartItem model module.
* @module model/CartItem
* @version v2
*/
export default class CartItem {
    /**
    * Constructs a new <code>CartItem</code>.
    * MSB Pay cart item model
    * @alias module:model/CartItem
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CartItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CartItem} obj Optional instance to populate.
    * @return {module:model/CartItem} The populated <code>CartItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CartItem();
                        
            
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('departmentId')) {
                obj['departmentId'] = ApiClient.convertToType(data['departmentId'], 'String');
            }
            if (data.hasOwnProperty('storeId')) {
                obj['storeId'] = ApiClient.convertToType(data['storeId'], 'String');
            }
            if (data.hasOwnProperty('itemId')) {
                obj['itemId'] = ApiClient.convertToType(data['itemId'], 'String');
            }
            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
            if (data.hasOwnProperty('paymentMethodId')) {
                obj['paymentMethodId'] = ApiClient.convertToType(data['paymentMethodId'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'String');
            }
            if (data.hasOwnProperty('unitPrice')) {
                obj['unitPrice'] = ApiClient.convertToType(data['unitPrice'], 'String');
            }
            if (data.hasOwnProperty('displaySalesTaxRate')) {
                obj['displaySalesTaxRate'] = ApiClient.convertToType(data['displaySalesTaxRate'], 'Number');
            }
            if (data.hasOwnProperty('salesTaxAmount')) {
                obj['salesTaxAmount'] = ApiClient.convertToType(data['salesTaxAmount'], 'Number');
            }
            if (data.hasOwnProperty('studentName')) {
                obj['studentName'] = ApiClient.convertToType(data['studentName'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [ItemProperty]);
            }
            if (data.hasOwnProperty('glAccountId')) {
                obj['glAccountId'] = ApiClient.convertToType(data['glAccountId'], 'String');
            }
        }
        return obj;
    }

    /**
    * ID for MySchoolBucks store that the sale should be recorded with for reporting [Required if no default for dev account]
    * @member {String} clientId
    */
    'clientId' = undefined;
    /**
    * ID for MySchoolBucks department that the sale should be recorded with for reporting
    * @member {String} departmentId
    */
    'departmentId' = undefined;
    /**
    * ID for MySchoolBucks store that the sale should be recorded with for reporting <i>[required if no default for dev account]</i>
    * @member {String} storeId
    */
    'storeId' = undefined;
    /**
    * ID for the MySchoolBucks item that the sale should be recorded with for reporting
    * @member {String} itemId
    */
    'itemId' = undefined;
    /**
    * Name of item that the line items should display to user at checkout and any receipts
    * @member {String} itemName
    */
    'itemName' = undefined;
    /**
    * ID for the MySchoolBucks payment method configuration that this cart should process through <i>[required if no default for dev account]</i>
    * @member {String} paymentMethodId
    */
    'paymentMethodId' = undefined;
    /**
    * Number of the items to purchase
    * @member {String} quantity
    */
    'quantity' = undefined;
    /**
    * Dollar amount price for each item in purchase
    * @member {String} unitPrice
    */
    'unitPrice' = undefined;
    /**
    * Percentage used to calculate sales tax. Used only for records, not used in calculation. Field 'salesTaxAmount' is used in calculation of total in checkout
    * @member {Number} displaySalesTaxRate
    */
    'displaySalesTaxRate' = undefined;
    /**
    * Amount to be added in checkout for sales tax
    * @member {Number} salesTaxAmount
    */
    'salesTaxAmount' = undefined;
    /**
    * Student name to be included in the checkout display and on receipts
    * @member {String} studentName
    */
    'studentName' = undefined;
    /**
    * Recorded for reporting
    * @member {String} reference
    */
    'reference' = undefined;
    /**
    * Array of additional properties to be recorded with the order and payment line items
    * @member {Array.<module:model/ItemProperty>} properties
    */
    'properties' = undefined;
    /**
    * GL Account to which the payments for this item will be applied
    * @member {String} glAccountId
    */
    'glAccountId' = undefined;




}
