/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ClientProperty model module.
* @module model/ClientProperty
* @version v2
*/
export default class ClientProperty {
    /**
    * Constructs a new <code>ClientProperty</code>.
    * A Name/Value pair, used when getting a list of properties for a client
    * @alias module:model/ClientProperty
    * @class
    * @param id {String} Identifier for the property. Used for API calls
    * @param name {String} Friendly name of the property
    */

    constructor(id, name) {
        
        
        this['id'] = id;
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>ClientProperty</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ClientProperty} obj Optional instance to populate.
    * @return {module:model/ClientProperty} The populated <code>ClientProperty</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientProperty();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * Identifier for the property. Used for API calls
    * @member {String} id
    */
    'id' = undefined;
    /**
    * Friendly name of the property
    * @member {String} name
    */
    'name' = undefined;




}
