/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MsbPayResponse from './MsbPayResponse';
import MsbPayResult from './MsbPayResult';

/**
* The InlineResponse2007 model module.
* @module model/InlineResponse2007
* @version v2
*/
export default class InlineResponse2007 {
    /**
    * Constructs a new <code>InlineResponse2007</code>.
    * @alias module:model/InlineResponse2007
    * @class
    * @extends module:model/MsbPayResponse
    */

    constructor() {
        MsbPayResponse.call(this);
        
        
    }

    /**
    * Constructs a <code>InlineResponse2007</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2007} obj Optional instance to populate.
    * @return {module:model/InlineResponse2007} The populated <code>InlineResponse2007</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2007();
            
            MsbPayResponse.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('paymentId')) {
                obj['paymentId'] = ApiClient.convertToType(data['paymentId'], 'String');
            }
            if (data.hasOwnProperty('cartId')) {
                obj['cartId'] = ApiClient.convertToType(data['cartId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Identifier of the payment that received refund request
    * @member {String} paymentId
    */
    'paymentId' = undefined;
    /**
    * Identifier of the cart containing the payment
    * @member {String} cartId
    */
    'cartId' = undefined;




}
