/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MsbPayResponse from './MsbPayResponse';
import MsbPayResult from './MsbPayResult';

/**
* The InlineResponse2003 model module.
* @module model/InlineResponse2003
* @version v2
*/
export default class InlineResponse2003 {
    /**
    * Constructs a new <code>InlineResponse2003</code>.
    * @alias module:model/InlineResponse2003
    * @class
    * @extends module:model/MsbPayResponse
    */

    constructor() {
        MsbPayResponse.call(this);
        
        
    }

    /**
    * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2003} obj Optional instance to populate.
    * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003();
            
            MsbPayResponse.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('responseBoolean')) {
                obj['responseBoolean'] = ApiClient.convertToType(data['responseBoolean'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * True/False value for the outcome of the method
    * @member {Boolean} responseBoolean
    */
    'responseBoolean' = undefined;




}
