/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CartOrder from './CartOrder';
import MsbPayResponse from './MsbPayResponse';
import MsbPayResult from './MsbPayResult';

/**
* The InlineResponse2005 model module.
* @module model/InlineResponse2005
* @version v2
*/
export default class InlineResponse2005 {
    /**
    * Constructs a new <code>InlineResponse2005</code>.
    * @alias module:model/InlineResponse2005
    * @class
    * @extends module:model/MsbPayResponse
    */

    constructor() {
        MsbPayResponse.call(this);
        
        
    }

    /**
    * Constructs a <code>InlineResponse2005</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2005} obj Optional instance to populate.
    * @return {module:model/InlineResponse2005} The populated <code>InlineResponse2005</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2005();
            
            MsbPayResponse.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('cartOrders')) {
                obj['cartOrders'] = ApiClient.convertToType(data['cartOrders'], [CartOrder]);
            }
        }
        return obj;
    }

    /**
    * List of Orders associated to the Cart processing
    * @member {Array.<module:model/CartOrder>} cartOrders
    */
    'cartOrders' = undefined;




}
