/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MsbPayResponse from './MsbPayResponse';
import MsbPayResult from './MsbPayResult';

/**
* The InlineResponse2004 model module.
* @module model/InlineResponse2004
* @version v2
*/
export default class InlineResponse2004 {
    /**
    * Constructs a new <code>InlineResponse2004</code>.
    * @alias module:model/InlineResponse2004
    * @class
    * @extends module:model/MsbPayResponse
    */

    constructor() {
        MsbPayResponse.call(this);
        
        
    }

    /**
    * Constructs a <code>InlineResponse2004</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2004} obj Optional instance to populate.
    * @return {module:model/InlineResponse2004} The populated <code>InlineResponse2004</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2004();
            
            MsbPayResponse.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('resultCodes')) {
                obj['resultCodes'] = ApiClient.convertToType(data['resultCodes'], ['String']);
            }
            if (data.hasOwnProperty('cartId')) {
                obj['cartId'] = ApiClient.convertToType(data['cartId'], 'String');
            }
            if (data.hasOwnProperty('paymentIds')) {
                obj['paymentIds'] = ApiClient.convertToType(data['paymentIds'], ['String']);
            }
        }
        return obj;
    }

    /**
    * Messages for the orders created from cart request
    * @member {Array.<String>} resultCodes
    */
    'resultCodes' = undefined;
    /**
    * Identifier of the cart processed by the request
    * @member {String} cartId
    */
    'cartId' = undefined;
    /**
    * Payment IDs for the cart processed by the request
    * @member {Array.<String>} paymentIds
    */
    'paymentIds' = undefined;




}
