/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MsbPayResponse from './MsbPayResponse';
import MsbPayResult from './MsbPayResult';
import MsbPayUser from './MsbPayUser';

/**
* The InlineResponse200 model module.
* @module model/InlineResponse200
* @version v2
*/
export default class InlineResponse200 {
    /**
    * Constructs a new <code>InlineResponse200</code>.
    * @alias module:model/InlineResponse200
    * @class
    * @extends module:model/MsbPayResponse
    */

    constructor() {
        MsbPayResponse.call(this);
        
        
    }

    /**
    * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse200} obj Optional instance to populate.
    * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();
            
            MsbPayResponse.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('user')) {
                obj['user'] = MsbPayUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MsbPayUser} user
    */
    'user' = undefined;




}
