/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ItemProperty model module.
* @module model/ItemProperty
* @version v2
*/
export default class ItemProperty {
    /**
    * Constructs a new <code>ItemProperty</code>.
    * Optional item property name and value
    * @alias module:model/ItemProperty
    * @class
    * @param name {String} Name of item property - this will be included in the order and payment item description on MySchoolBucks
    * @param value {String} Value of named item property - this will be included in the order and payment item description on MySchoolBucks
    */

    constructor(name, value) {
        
        
        this['name'] = name;
        this['value'] = value;
        
    }

    /**
    * Constructs a <code>ItemProperty</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ItemProperty} obj Optional instance to populate.
    * @return {module:model/ItemProperty} The populated <code>ItemProperty</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ItemProperty();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('displayResponse')) {
                obj['displayResponse'] = ApiClient.convertToType(data['displayResponse'], 'String');
            }
        }
        return obj;
    }

    /**
    * Name of item property - this will be included in the order and payment item description on MySchoolBucks
    * @member {String} name
    */
    'name' = undefined;
    /**
    * Value of named item property - this will be included in the order and payment item description on MySchoolBucks
    * @member {String} value
    */
    'value' = undefined;
    /**
    * Specifies whether or not to display the property to the user. Valid values are \"visible\", \"hidden\", or empty/null
    * @member {String} displayResponse
    */
    'displayResponse' = undefined;




}
