/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MsbPayUserClient from './MsbPayUserClient';

/**
* The MsbPayUser model module.
* @module model/MsbPayUser
* @version v2
*/
export default class MsbPayUser {
    /**
    * Constructs a new <code>MsbPayUser</code>.
    * @alias module:model/MsbPayUser
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MsbPayUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MsbPayUser} obj Optional instance to populate.
    * @return {module:model/MsbPayUser} The populated <code>MsbPayUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MsbPayUser();
                        
            
            if (data.hasOwnProperty('defaultClientId')) {
                obj['defaultClientId'] = ApiClient.convertToType(data['defaultClientId'], 'String');
            }
            if (data.hasOwnProperty('developerAccountId')) {
                obj['developerAccountId'] = ApiClient.convertToType(data['developerAccountId'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('clients')) {
                obj['clients'] = ApiClient.convertToType(data['clients'], [MsbPayUserClient]);
            }
        }
        return obj;
    }

    /**
    * ID for MySchoolBucks top level organizational unit this developer account is assigned to as a default (if null, no default is set)
    * @member {String} defaultClientId
    */
    'defaultClientId' = undefined;
    /**
    * Developer account ID
    * @member {String} developerAccountId
    */
    'developerAccountId' = undefined;
    /**
    * First name for the developer account holder
    * @member {String} firstName
    */
    'firstName' = undefined;
    /**
    * Last name of the developer account holder
    * @member {String} lastName
    */
    'lastName' = undefined;
    /**
    * Email address for the developer account holder
    * @member {String} email
    */
    'email' = undefined;
    /**
    * MSB clients and default settings for each
    * @member {Array.<module:model/MsbPayUserClient>} clients
    */
    'clients' = undefined;




}
