/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MsbPayResult from './MsbPayResult';

/**
* The MsbPayResponse model module.
* @module model/MsbPayResponse
* @version v2
*/
export default class MsbPayResponse {
    /**
    * Constructs a new <code>MsbPayResponse</code>.
    * @alias module:model/MsbPayResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MsbPayResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MsbPayResponse} obj Optional instance to populate.
    * @return {module:model/MsbPayResponse} The populated <code>MsbPayResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MsbPayResponse();
                        
            
            if (data.hasOwnProperty('result')) {
                obj['result'] = MsbPayResult.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MsbPayResult} result
    */
    'result' = undefined;
    /**
    * Error messages supplied if there are issues with method.
    * @member {Array.<String>} errors
    */
    'errors' = undefined;




}
