/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MsbPayUserClient model module.
* @module model/MsbPayUserClient
* @version v2
*/
export default class MsbPayUserClient {
    /**
    * Constructs a new <code>MsbPayUserClient</code>.
    * Describes client settings assigned to the developer account
    * @alias module:model/MsbPayUserClient
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MsbPayUserClient</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MsbPayUserClient} obj Optional instance to populate.
    * @return {module:model/MsbPayUserClient} The populated <code>MsbPayUserClient</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MsbPayUserClient();
                        
            
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('clientId')) {
                obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
            }
            if (data.hasOwnProperty('departmentId')) {
                obj['departmentId'] = ApiClient.convertToType(data['departmentId'], 'String');
            }
            if (data.hasOwnProperty('storeId')) {
                obj['storeId'] = ApiClient.convertToType(data['storeId'], 'String');
            }
            if (data.hasOwnProperty('paymentMethodId')) {
                obj['paymentMethodId'] = ApiClient.convertToType(data['paymentMethodId'], 'String');
            }
        }
        return obj;
    }

    /**
    * Indicates if the client is currently enabled for the developer account
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * ID for MySchoolBucks top level organizational unit
    * @member {String} clientId
    */
    'clientId' = undefined;
    /**
    * Default ID for MySchoolBucks department that the sale for this client will be recorded (if null, no default is set)
    * @member {String} departmentId
    */
    'departmentId' = undefined;
    /**
    * Default store that the sale for this client will be recorded with (if null, no default is set)
    * @member {String} storeId
    */
    'storeId' = undefined;
    /**
    * Default payment method that sales for this client will be processed by (if null, no default is set)
    * @member {String} paymentMethodId
    */
    'paymentMethodId' = undefined;




}
