/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OrderStatus.
* @enum {}
* @readonly
*/
export default class OrderStatus {
        /**
         * value: "active"
         * @const
         */
        active = "active";

        /**
         * value: "canceled"
         * @const
         */
        canceled = "canceled";

        /**
         * value: "closed"
         * @const
         */
        closed = "closed";

        /**
         * value: "declined"
         * @const
         */
        declined = "declined";

        /**
         * value: "pending"
         * @const
         */
        pending = "pending";

        /**
         * value: "review"
         * @const
         */
        review = "review";

        /**
         * value: "void"
         * @const
         */
        void = "void";


    /**
    * Returns a <code>OrderStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OrderStatus} The enum <code>OrderStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
