/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayApiEventType.
* @enum {}
* @readonly
*/
export default class PayApiEventType {
        /**
         * value: "ping"
         * @const
         */
        ping = "ping";

        /**
         * value: "cart.authorized"
         * @const
         */
        cartAuthorized = "cart.authorized";

        /**
         * value: "cart.processed"
         * @const
         */
        cartProcessed = "cart.processed";

        /**
         * value: "cart.canceled"
         * @const
         */
        cartCanceled = "cart.canceled";

        /**
         * value: "payment.settled"
         * @const
         */
        paymentSettled = "payment.settled";

        /**
         * value: "payment.authorized"
         * @const
         */
        paymentAuthorized = "payment.authorized";

        /**
         * value: "payment.failed"
         * @const
         */
        paymentFailed = "payment.failed";

        /**
         * value: "payment.refunded"
         * @const
         */
        paymentRefunded = "payment.refunded";


    /**
    * Returns a <code>PayApiEventType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PayApiEventType} The enum <code>PayApiEventType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
