/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayApiEventType from './PayApiEventType';

/**
* The WebhookSubscription model module.
* @module model/WebhookSubscription
* @version v2
*/
export default class WebhookSubscription {
    /**
    * Constructs a new <code>WebhookSubscription</code>.
    * MSB webhook subscription model
    * @alias module:model/WebhookSubscription
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>WebhookSubscription</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WebhookSubscription} obj Optional instance to populate.
    * @return {module:model/WebhookSubscription} The populated <code>WebhookSubscription</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookSubscription();
                        
            
            if (data.hasOwnProperty('notifyUrl')) {
                obj['notifyUrl'] = ApiClient.convertToType(data['notifyUrl'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = PayApiEventType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'String');
            }
        }
        return obj;
    }

    /**
    * URL to notify of change
    * @member {String} notifyUrl
    */
    'notifyUrl' = undefined;
    /**
    * @member {module:model/PayApiEventType} type
    */
    'type' = undefined;
    /**
    * Will be \"true\" if webhook subscription is enabled, \"false\" otherwise
    * @member {Boolean} isEnabled
    */
    'isEnabled' = undefined;
    /**
    * ID for the webhook subscription
    * @member {String} subscriptionId
    */
    'subscriptionId' = undefined;




}
