/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import InlineResponse20010 from '../model/InlineResponse20010';

/**
* Departments service.
* @module api/DepartmentsApi
* @version v2
*/
export default class DepartmentsApi {

    /**
    * Constructs a new DepartmentsApi. 
    * @alias module:api/DepartmentsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the clientsClientIdDepartmentsGet operation.
     * @callback module:api/DepartmentsApi~clientsClientIdDepartmentsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20010} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get department IDs
     * Returns IDs for departments associated with the client
     * @param {Object} opts Optional parameters
     * @param {module:api/DepartmentsApi~clientsClientIdDepartmentsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20010}
     */
    clientsClientIdDepartmentsGet(authorization, clientId, opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        'clientId': clientId
      };
      let queryParams = {
        'page': opts['page'],
        'rowCount': opts['rowCount'],
        'searchText': opts['searchText']
      };
      let headerParams = {
        'Authorization': authorization
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse20010;

      return this.apiClient.callApi(
        '/clients/{clientId}/departments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
