/**
 * MSB Pay API
 * API specification for payment processing via the MySchoolBucks.com cart checkout. <br /> <a href=\"MSBPayAPI-v2-changelog.txt\">Changelog</a>
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MsbPayApi);
  }
}(this, function(expect, MsbPayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MsbPayApi.Cart();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Cart', function() {
    it('should create an instance of Cart', function() {
      // uncomment below and update the code to test Cart
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be.a(MsbPayApi.Cart);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property createdDate (base name: "createdDate")', function() {
      // uncomment below and update the code to test the property createdDate
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "lastUpdated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property redirectUrl (base name: "redirectUrl")', function() {
      // uncomment below and update the code to test the property redirectUrl
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property returnToSiteUrl (base name: "returnToSiteUrl")', function() {
      // uncomment below and update the code to test the property returnToSiteUrl
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property checkoutUrl (base name: "checkoutUrl")', function() {
      // uncomment below and update the code to test the property checkoutUrl
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property allowDuplicatePayments (base name: "allowDuplicatePayments")', function() {
      // uncomment below and update the code to test the property allowDuplicatePayments
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property loginPolicy (base name: "loginPolicy")', function() {
      // uncomment below and update the code to test the property loginPolicy
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property checkoutStyle (base name: "checkoutStyle")', function() {
      // uncomment below and update the code to test the property checkoutStyle
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property cartItems (base name: "cartItems")', function() {
      // uncomment below and update the code to test the property cartItems
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property paymentPreauthPolicy (base name: "paymentPreauthPolicy")', function() {
      // uncomment below and update the code to test the property paymentPreauthPolicy
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

    it('should have the property webhookSubscriptions (base name: "webhookSubscriptions")', function() {
      // uncomment below and update the code to test the property webhookSubscriptions
      //var instane = new MsbPayApi.Cart();
      //expect(instance).to.be();
    });

  });

}));
